package com.myteam.stunnergeneration;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class DataObject implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "DATAOBJECT_ID_GENERATOR")
    @javax.persistence.Id
    @javax.persistence.SequenceGenerator(sequenceName = "DATAOBJECT_ID_SEQ", name = "DATAOBJECT_ID_GENERATOR")
    private java.lang.Long id;

    public DataObject() {
    }
    
    public DataObject(java.lang.Long id) {
        this.id = id;
    }

    public java.lang.Long getId() {
        return this.id;
    }
    
    public void setId(java.lang.Long id) {
        this.id = id;
    }




}